FROM node:latest

RUN apt-get update && apt-get install -y nodejs-legacy

RUN npm install -g express
RUN npm install -g express-generator

#Creation du repertoire du projet
#RUN cd /opt
#RUN express leaflet_map

#maj du fichier package.json
#ADD conf/package.json /opt/leaflet_map/package.json

#Installation des dépendances
#RUN cd leaflet_map
#RUN echo $pwd
#RUN npm install


